# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.35
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _ubigraph
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


ubigraph_new_vertex = _ubigraph.ubigraph_new_vertex
ubigraph_new_edge = _ubigraph.ubigraph_new_edge
ubigraph_remove_vertex = _ubigraph.ubigraph_remove_vertex
ubigraph_remove_edge = _ubigraph.ubigraph_remove_edge
ubigraph_new_vertex_w_id = _ubigraph.ubigraph_new_vertex_w_id
ubigraph_new_edge_w_id = _ubigraph.ubigraph_new_edge_w_id
ubigraph_clear = _ubigraph.ubigraph_clear
ubigraph_set_vertex_attribute = _ubigraph.ubigraph_set_vertex_attribute
ubigraph_change_vertex_style = _ubigraph.ubigraph_change_vertex_style
ubigraph_new_vertex_style = _ubigraph.ubigraph_new_vertex_style
ubigraph_new_vertex_style_w_id = _ubigraph.ubigraph_new_vertex_style_w_id
ubigraph_set_vertex_style_attribute = _ubigraph.ubigraph_set_vertex_style_attribute
ubigraph_set_edge_attribute = _ubigraph.ubigraph_set_edge_attribute
ubigraph_change_edge_style = _ubigraph.ubigraph_change_edge_style
ubigraph_new_edge_style = _ubigraph.ubigraph_new_edge_style
ubigraph_new_edge_style_w_id = _ubigraph.ubigraph_new_edge_style_w_id
ubigraph_set_edge_style_attribute = _ubigraph.ubigraph_set_edge_style_attribute


