/* Generated By:JJTree: Do not edit this line. ASTArrayInitializer.java */

public class ASTArrayInitializer extends SimpleNode {
  public ASTArrayInitializer(int id) {
    super(id);
  }

  public ASTArrayInitializer(JavaParser p, int id) {
    super(p, id);
  }

}
