/* Generated By:JJTree: Do not edit this line. ASTAdditiveExpression.java */

public class ASTAdditiveExpression extends SimpleNode {
  public ASTAdditiveExpression(int id) {
    super(id);
  }

  public ASTAdditiveExpression(JavaParser p, int id) {
    super(p, id);
  }

}
