/* Generated By:JJTree: Do not edit this line. ASTAnnotationTypeDeclaration.java */

public class ASTAnnotationTypeDeclaration extends SimpleNode {
  public ASTAnnotationTypeDeclaration(int id) {
    super(id);
  }

  public ASTAnnotationTypeDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
