/* Generated By:JJTree: Do not edit this line. ASTAnnotation.java */

public class ASTAnnotation extends SimpleNode {
  public ASTAnnotation(int id) {
    super(id);
  }

  public ASTAnnotation(JavaParser p, int id) {
    super(p, id);
  }

}
