/* Generated By:JJTree: Do not edit this line. ASTArrayDimsAndInits.java */

public class ASTArrayDimsAndInits extends SimpleNode {
  public ASTArrayDimsAndInits(int id) {
    super(id);
  }

  public ASTArrayDimsAndInits(JavaParser p, int id) {
    super(p, id);
  }

}
