/* Generated By:JJTree: Do not edit this line. ASTAndExpression.java */

public class ASTAndExpression extends SimpleNode {
  public ASTAndExpression(int id) {
    super(id);
  }

  public ASTAndExpression(JavaParser p, int id) {
    super(p, id);
  }

}
