/* Generated By:JJTree: Do not edit this line. ASTAssignmentOperator.java */

public class ASTAssignmentOperator extends SimpleNode {
  public ASTAssignmentOperator(int id) {
    super(id);
  }

  public ASTAssignmentOperator(JavaParser p, int id) {
    super(p, id);
  }

}
