/* Generated By:JJTree: Do not edit this line. ASTBlock.java */

public class ASTBlock extends SimpleNode {
  public ASTBlock(int id) {
    super(id);
  }

  public ASTBlock(JavaParser p, int id) {
    super(p, id);
  }

}
