/* Generated By:JJTree: Do not edit this line. ASTBlockStatement.java */

public class ASTBlockStatement extends SimpleNode {
  public ASTBlockStatement(int id) {
    super(id);
  }

  public ASTBlockStatement(JavaParser p, int id) {
    super(p, id);
  }

}
