/* Generated By:JJTree: Do not edit this line. ASTCastExpression.java */

public class ASTCastExpression extends SimpleNode {
  public ASTCastExpression(int id) {
    super(id);
  }

  public ASTCastExpression(JavaParser p, int id) {
    super(p, id);
  }

}
