/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceBody.java */

public class ASTClassOrInterfaceBody extends SimpleNode {
  public ASTClassOrInterfaceBody(int id) {
    super(id);
  }

  public ASTClassOrInterfaceBody(JavaParser p, int id) {
    super(p, id);
  }

}
