/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceType.java */

public class ASTClassOrInterfaceType extends SimpleNode {
  public ASTClassOrInterfaceType(int id) {
    super(id);
  }

  public ASTClassOrInterfaceType(JavaParser p, int id) {
    super(p, id);
  }

}
