/* Generated By:JJTree: Do not edit this line. ASTConditionalOrExpression.java */

public class ASTConditionalOrExpression extends SimpleNode {
  public ASTConditionalOrExpression(int id) {
    super(id);
  }

  public ASTConditionalOrExpression(JavaParser p, int id) {
    super(p, id);
  }

}
