/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceDeclaration.java */

public class ASTClassOrInterfaceDeclaration extends SimpleNode {
  public ASTClassOrInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTClassOrInterfaceDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
