/* Generated By:JJTree: Do not edit this line. ASTConditionalAndExpression.java */

public class ASTConditionalAndExpression extends SimpleNode {
  public ASTConditionalAndExpression(int id) {
    super(id);
  }

  public ASTConditionalAndExpression(JavaParser p, int id) {
    super(p, id);
  }

}
