/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceBodyDeclaration.java */

public class ASTClassOrInterfaceBodyDeclaration extends SimpleNode {
  public ASTClassOrInterfaceBodyDeclaration(int id) {
    super(id);
  }

  public ASTClassOrInterfaceBodyDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
