/* Generated By:JJTree: Do not edit this line. ASTCastLookahead.java */

public class ASTCastLookahead extends SimpleNode {
  public ASTCastLookahead(int id) {
    super(id);
  }

  public ASTCastLookahead(JavaParser p, int id) {
    super(p, id);
  }

}
