/* Generated By:JJTree: Do not edit this line. ASTCompilationUnit.java */

public class ASTCompilationUnit extends SimpleNode {
  public ASTCompilationUnit(int id) {
    super(id);
  }

  public ASTCompilationUnit(JavaParser p, int id) {
    super(p, id);
  }

}
