/* Generated By:JJTree: Do not edit this line. ASTEnumConstant.java */

public class ASTEnumConstant extends SimpleNode {
  public ASTEnumConstant(int id) {
    super(id);
  }

  public ASTEnumConstant(JavaParser p, int id) {
    super(p, id);
  }

}
