/* Generated By:JJTree: Do not edit this line. ASTEnumDeclaration.java */

public class ASTEnumDeclaration extends SimpleNode {
  public ASTEnumDeclaration(int id) {
    super(id);
  }

  public ASTEnumDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
