/* Generated By:JJTree: Do not edit this line. ASTExclusiveOrExpression.java */

public class ASTExclusiveOrExpression extends SimpleNode {
  public ASTExclusiveOrExpression(int id) {
    super(id);
  }

  public ASTExclusiveOrExpression(JavaParser p, int id) {
    super(p, id);
  }

}
