/* Generated By:JJTree: Do not edit this line. ASTEmptyStatement.java */

public class ASTEmptyStatement extends SimpleNode {
  public ASTEmptyStatement(int id) {
    super(id);
  }

  public ASTEmptyStatement(JavaParser p, int id) {
    super(p, id);
  }

}
