/* Generated By:JJTree: Do not edit this line. ASTExplicitConstructorInvocation.java */

public class ASTExplicitConstructorInvocation extends SimpleNode {
  public ASTExplicitConstructorInvocation(int id) {
    super(id);
  }

  public ASTExplicitConstructorInvocation(JavaParser p, int id) {
    super(p, id);
  }

}
