/* Generated By:JJTree: Do not edit this line. ASTForUpdate.java */

public class ASTForUpdate extends SimpleNode {
  public ASTForUpdate(int id) {
    super(id);
  }

  public ASTForUpdate(JavaParser p, int id) {
    super(p, id);
  }

}
