/* Generated By:JJTree: Do not edit this line. ASTLocalVariableDeclaration.java */

public class ASTLocalVariableDeclaration extends SimpleNode {
  public Token name;

  public ASTLocalVariableDeclaration(int id) {
    super(id);
  }

  public ASTLocalVariableDeclaration(JavaParser p, int id) {
    super(p, id);
  }

  public String toString()
  {
    return super.toString() + "[" + name.toString() + "]";
  }
}
