/* Generated By:JJTree: Do not edit this line. ASTLabeledStatement.java */

public class ASTLabeledStatement extends SimpleNode {
  public ASTLabeledStatement(int id) {
    super(id);
  }

  public ASTLabeledStatement(JavaParser p, int id) {
    super(p, id);
  }

}
