/* Generated By:JJTree: Do not edit this line. ASTLiteral.java */

public class ASTLiteral extends SimpleNode {
  public ASTLiteral(int id) {
    super(id);
  }

  public ASTLiteral(JavaParser p, int id) {
    super(p, id);
  }

}
