/* Generated By:JJTree: Do not edit this line. ASTMemberValue.java */

public class ASTMemberValue extends SimpleNode {
  public ASTMemberValue(int id) {
    super(id);
  }

  public ASTMemberValue(JavaParser p, int id) {
    super(p, id);
  }

}
