/* Generated By:JJTree: Do not edit this line. ASTMultiplicativeExpression.java */

public class ASTMultiplicativeExpression extends SimpleNode {
  public ASTMultiplicativeExpression(int id) {
    super(id);
  }

  public ASTMultiplicativeExpression(JavaParser p, int id) {
    super(p, id);
  }

}
