/* Generated By:JJTree: Do not edit this line. ASTMemberSelector.java */

public class ASTMemberSelector extends SimpleNode {
  public ASTMemberSelector(int id) {
    super(id);
  }

  public ASTMemberSelector(JavaParser p, int id) {
    super(p, id);
  }

}
