/* Generated By:JJTree: Do not edit this line. ASTModifiers.java */

public class ASTModifiers extends SimpleNode {
  public ASTModifiers(int id) {
    super(id);
  }

  public ASTModifiers(JavaParser p, int id) {
    super(p, id);
  }

}
