/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarator.java */

public class ASTMethodDeclarator extends SimpleNode {
  public String name;

  public ASTMethodDeclarator(int id) {
    super(id);
    graph.setVertexAttribute(hashCode(), "color", "#ff0000");
  }

  public ASTMethodDeclarator(JavaParser p, int id) {
    super(p, id);
  }

  public String toString()
  {
    if (name == null)
      return super.toString();
    else
      return super.toString() + "[" + name.toString() + "]";
  }

}
