/* Generated By:JJTree: Do not edit this line. ASTMemberValueArrayInitializer.java */

public class ASTMemberValueArrayInitializer extends SimpleNode {
  public ASTMemberValueArrayInitializer(int id) {
    super(id);
  }

  public ASTMemberValueArrayInitializer(JavaParser p, int id) {
    super(p, id);
  }

}
