/* Generated By:JJTree: Do not edit this line. ASTMemberValuePair.java */

public class ASTMemberValuePair extends SimpleNode {
  public ASTMemberValuePair(int id) {
    super(id);
  }

  public ASTMemberValuePair(JavaParser p, int id) {
    super(p, id);
  }

}
