/* Generated By:JJTree: Do not edit this line. ASTNormalAnnotation.java */

public class ASTNormalAnnotation extends SimpleNode {
  public ASTNormalAnnotation(int id) {
    super(id);
  }

  public ASTNormalAnnotation(JavaParser p, int id) {
    super(p, id);
  }

}
