/* Generated By:JJTree: Do not edit this line. ASTName.java */

public class ASTName extends SimpleNode {
  public String name;

  public ASTName(int id) {
    super(id);
  }

  public ASTName(JavaParser p, int id) {
    super(p, id);
  }

  public String toString()
  {
    if (name == null)
      return super.toString();
    else
      return super.toString() + "[" + name.toString() + "]";
  }

}
