/* Generated By:JJTree: Do not edit this line. ASTNameList.java */

public class ASTNameList extends SimpleNode {
  public ASTNameList(int id) {
    super(id);
  }

  public ASTNameList(JavaParser p, int id) {
    super(p, id);
  }

}
