/* Generated By:JJTree: Do not edit this line. ASTPrimaryPrefix.java */

public class ASTPrimaryPrefix extends SimpleNode {
  public ASTPrimaryPrefix(int id) {
    super(id);
  }

  public ASTPrimaryPrefix(JavaParser p, int id) {
    super(p, id);
  }

}
