/* Generated By:JJTree: Do not edit this line. ASTPrimaryExpression.java */

public class ASTPrimaryExpression extends SimpleNode {
  public ASTPrimaryExpression(int id) {
    super(id);
  }

  public ASTPrimaryExpression(JavaParser p, int id) {
    super(p, id);
  }

}
