/* Generated By:JJTree: Do not edit this line. ASTReturnStatement.java */

public class ASTReturnStatement extends SimpleNode {
  public ASTReturnStatement(int id) {
    super(id);
  }

  public ASTReturnStatement(JavaParser p, int id) {
    super(p, id);
  }

}
