/* Generated By:JJTree: Do not edit this line. ASTRSIGNEDSHIFT.java */

public class ASTRSIGNEDSHIFT extends SimpleNode {
  public ASTRSIGNEDSHIFT(int id) {
    super(id);
  }

  public ASTRSIGNEDSHIFT(JavaParser p, int id) {
    super(p, id);
  }

}
