/* Generated By:JJTree: Do not edit this line. ASTRelationalExpression.java */

public class ASTRelationalExpression extends SimpleNode {
  public ASTRelationalExpression(int id) {
    super(id);
  }

  public ASTRelationalExpression(JavaParser p, int id) {
    super(p, id);
  }

}
