/* Generated By:JJTree: Do not edit this line. ASTRUNSIGNEDSHIFT.java */

public class ASTRUNSIGNEDSHIFT extends SimpleNode {
  public ASTRUNSIGNEDSHIFT(int id) {
    super(id);
  }

  public ASTRUNSIGNEDSHIFT(JavaParser p, int id) {
    super(p, id);
  }

}
