/* Generated By:JJTree: Do not edit this line. ASTSingleMemberAnnotation.java */

public class ASTSingleMemberAnnotation extends SimpleNode {
  public ASTSingleMemberAnnotation(int id) {
    super(id);
  }

  public ASTSingleMemberAnnotation(JavaParser p, int id) {
    super(p, id);
  }

}
