/* Generated By:JJTree: Do not edit this line. ASTStatementExpression.java */

public class ASTStatementExpression extends SimpleNode {
  public ASTStatementExpression(int id) {
    super(id);
  }

  public ASTStatementExpression(JavaParser p, int id) {
    super(p, id);
  }

}
