/* Generated By:JJTree: Do not edit this line. ASTStatement.java */

public class ASTStatement extends SimpleNode {
  public ASTStatement(int id) {
    super(id);
  }

  public ASTStatement(JavaParser p, int id) {
    super(p, id);
  }

}
