/* Generated By:JJTree: Do not edit this line. ASTShiftExpression.java */

public class ASTShiftExpression extends SimpleNode {
  public ASTShiftExpression(int id) {
    super(id);
  }

  public ASTShiftExpression(JavaParser p, int id) {
    super(p, id);
  }

}
