/* Generated By:JJTree: Do not edit this line. ASTTypeDeclaration.java */

public class ASTTypeDeclaration extends SimpleNode {
  public ASTTypeDeclaration(int id) {
    super(id);
  }

  public ASTTypeDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
