/* Generated By:JJTree: Do not edit this line. ASTTypeArgument.java */

public class ASTTypeArgument extends SimpleNode {
  public ASTTypeArgument(int id) {
    super(id);
  }

  public ASTTypeArgument(JavaParser p, int id) {
    super(p, id);
  }

}
