/* Generated By:JJTree: Do not edit this line. ASTTryStatement.java */

public class ASTTryStatement extends SimpleNode {
  public ASTTryStatement(int id) {
    super(id);
  }

  public ASTTryStatement(JavaParser p, int id) {
    super(p, id);
  }

}
