/* Generated By:JJTree: Do not edit this line. ASTTypeParameter.java */

public class ASTTypeParameter extends SimpleNode {
  public ASTTypeParameter(int id) {
    super(id);
  }

  public ASTTypeParameter(JavaParser p, int id) {
    super(p, id);
  }

}
