/* Generated By:JJTree: Do not edit this line. ASTTypeBound.java */

public class ASTTypeBound extends SimpleNode {
  public ASTTypeBound(int id) {
    super(id);
  }

  public ASTTypeBound(JavaParser p, int id) {
    super(p, id);
  }

}
