/* Generated By:JJTree: Do not edit this line. ASTVariableDeclaratorId.java */

public class ASTVariableDeclaratorId extends SimpleNode {
  public String name;

  public ASTVariableDeclaratorId(int id) {
    super(id);
  }

  public ASTVariableDeclaratorId(JavaParser p, int id) {
    super(p, id);
  }

  public String toString()
  {
    if (name == null)
      return super.toString();
    else
      return super.toString() + "[" + name.toString() + "]";
  }
}
