/* Generated By:JJTree: Do not edit this line. ASTVariableInitializer.java */

public class ASTVariableInitializer extends SimpleNode {
  public ASTVariableInitializer(int id) {
    super(id);
  }

  public ASTVariableInitializer(JavaParser p, int id) {
    super(p, id);
  }

}
