/* Generated By:JJTree: Do not edit this line. ASTWildcardBounds.java */

public class ASTWildcardBounds extends SimpleNode {
  public ASTWildcardBounds(int id) {
    super(id);
  }

  public ASTWildcardBounds(JavaParser p, int id) {
    super(p, id);
  }

}
